const data = {
  "Binary Explorers": ["Internet", "Algorithm", "Automation", "Augmented"],
  "Data Diviners": ["Blockchain", "Computing", "Cryptography", "CyberSecurity"],
  "Electric Expedition": [
    "Digitalization",
    "Encryption",
    "Firewall",
    "Framework",
  ],
  "Code Crusaders": ["Gigabyte", "Infrastructure", "Hypertext", "JavaScript"],
  "Pixel Pathfinders": ["Kernel", "Machine", "Malware", "Network"],
  "Circuit Chasers": ["Operation", "Password", "Platform", "Markup"],
  "Digital Detectives": ["Protocol", "Quantum", "Robotics", "Sandbox"],
  "Silicon Seekers": ["Script", "Keyword", "Notation", "Local"],
  Codebreakers: ["Query", "Storage", "Terminal", "Virtulization"],
  "Algorithm Avengers": ["Virtual", "Trojan", "Resource", "Private"],
  "Robo Raiders": ["Wireless", "Analytics", "Extensible", "Application"],
  "Net Navigators": ["Programming", "Interface", "Biometrics", "Cache"],
  "Cyber Sleuths": ["Compiler", "Debugger", "Domain", "Ethernet"],
  "Techno Trackers": ["Firmware", "Graphics", "Hyperlink", "Service"],
  "Gadget Gurus": ["Object", "Server", "Unicode", "Transmission"],
  "Byte Busters": ["Software", "Global", "Repository", "Pascal"],
  "Hackathon Heroes": ["Spreadsheet", "Independent", "Development", "Latency"],
  "Geek Squad": ["System", "Input", "Megabyte", "Address"],
  "Tech Trailblazers": ["Output", "Source", "Packet", "Response"],
  "Software Scavengers": ["Router", "Vector", "Scalable", "Serial"],
  "Debugging Dynasty": ["Parallel", "Scripting", "Agile", "Backup"],
  "Cyber Explorers": ["Protected", "Vulnerability", "Update", "Artificial"],
  "Virtual Voyagers": ["Database", "Hosting", "Browser", "Sensor"],
  "Robotics Rangers": ["Token", "Mining", "Hashtree", "Binary"],
  "Network Ninjas": ["Digital", "Analog", "Platform", "Version"],
  "Tech Detectives": ["Visulization", "Gateway", "Dashboard", "Deployment"],
  "Software Sherpas": [
    "Integration",
    "Prototype",
    "Accesbility",
    "Optimization",
  ],
  "Web Warriors": ["Autherization", "Search", "Balancer", "Usability"],
  "Software Safari": ["Anamoly", "Pipeline", "Serverless", "Conversion"],
  "Neural Navigators": ["Engine", "Detection", "Retention", "Learning"],
};

export default data;
