const fillerData = [
  "Holography",
  "Telecommunication",
  "Cryptography",
  "Signal",
  "Module",
  "Embedded",
  "CyberSecurity",
  "Analysis",
  "Process",
  "Webcam",
  "Simulation",
  "Hologram",
  "Navigation",
  "Regulation",
  "Bandwidth",
  "Transistor",
  "Spectrometer",
  "Antenna",
  "Processor",
  "Circuit",
  "Joystick",
  "Datagram",
  "Connectivity",
  "Efficiency",
  "Conductor",
];

export default fillerData;
